/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CS2263.HW;

import com.google.common.graph.MutableNetwork;
import com.google.common.graph.NetworkBuilder;

public class myGraph {
    void accept(Visitor visitor);

    Person Phil = new Person("Phil", 23, "chocolate");
    Person Rob = new Person("Rob", 18, "Rocky Road");
    Person Diana = new Person("Diana", 25, "Huckleberry");
    Relation Married = new Relation("is married to");
    Relation Friends = new Relation("is friends with");
    Relation Siblings = new Relation("is siblings with");

    MutableNetwork<Person, Relation> myGraph =
            NetworkBuilder.directed().allowsParallelEdges(true).build();
    myGraph.addNode(Phil);
    myGraph.addNode(Rob);
    myGraph.addNode(Diana);
    myGraph.addEdge(Phil, Rob, Friends);
    myGraph.addEdge(Phil, Diana, Married);
    myGraph.addEdge(Diana, Rob, Siblings);

    public static void main(String[] args) {
        System.out.println("This is meant to eventually print relations");
        System.out.println("This is meant to eventually print the relation type summary");
    }
}
